### ISSUE TITLE
Error: Could not find or load main class pattypan.Main

### ISSUE THREAD

**Issue by nemobis** [yarl/pattypan#10]
In OpenJDK 1.8.0_92, I cannot launch the jar:
```
$ LANG=EN java -jar pattypan.jar                                                                                                                    
Error: Could not find or load main class pattypan.Main 
$ java -version
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (build 1.8.0_92-b14)
OpenJDK 64-Bit Server VM (build 25.92-b14, mixed mode)
```

**Comment by yarl** [comment]
It's on Ubuntu? I will download VM and take a look at it.

**Comment by nemobis** [comment]
Yes, this was Ubuntu

**Comment by yarl** [comment]
OK, it looks like OpenJDK 8 do not contains JavaFX equivalent. Please try to install package below:

```
sudo apt-get install openjfx
```

**Comment by yarl** [comment]
I'm closing this one, please reopen if you will have problems in the future.

**Comment by nemobis** [comment]
I've not yet tested because I didn't quickly find openjfx for Fedora 
(see also 
https://ask.fedoraproject.org/en/question/63037/is-there-openjfx-for-fedora-yet/ 
) and I didn't have access to the Ubuntu machine.

In any case, it would be good for the README to state the actual 
requirements of this software.

**Comment by yarl** [comment]
> In any case, it would be good for the README to state the actual requirements of this software.

Definitely. I started documentation some time ago [at project wiki]( https://github.com/yarl/pattypan/wiki/Run). At some point it can be included to the repo and copied to Commons documentation.

**Comment by coderwassananmol** [comment]
#78 This pull request adds the documentation for the same.
