### ISSUE TITLE
Spreadsheet possibly corrupt after editing

### ISSUE THREAD

**Issue by rayasharbain** [yarl/pattypan#103]
After editing the spreadsheet and exporting as a .xls file, PattyPan says that there are problems opening the file with a possibility of it being corrupt. Screenshot, spreadsheet, example media file, and log file attached.
<img width="793" alt="Screenshot 2019-10-09 at 16 47 00" src="https://user-images.githubusercontent.com/25263499/66487201-99642200-eab4-11e9-90b1-3db7bf0ce46e.png">
[pattypan.log](https://github.com/yarl/pattypan/files/3707643/pattypan.log)
[pattypan 2019-10-09 16_33_11.xlsx](https://github.com/yarl/pattypan/files/3707650/pattypan.2019-10-09.16_33_11.xlsx)
![96H60LISP-THIS IMAGE DOES NOT BELONG TO ME](https://user-images.githubusercontent.com/25263499/66487369-e0521780-eab4-11e9-9f26-fd67fc91c6c6.JPG)

**Comment by yarl** [comment]
- you cannot use spaces in headers, change `camera coord` to `camera_coord` (also in the second spreadsheet tab)
- `category?trim` header should be just `category`

**Comment by rayasharbain** [comment]
Turns out that's the error, thank you :-)
