### ISSUE TITLE
files from local drive should be loaded to spreadsheet in alphabetical order

### ISSUE THREAD

**Issue by yarl** [yarl/pattypan#109]
it may be OS specific, reported on Ubuntu

**Comment by JoKalliauer** [comment]
Same with Fedora 32 ([5.11.11-100.fc32.x86_64](https://fedora.pkgs.org/32/fedora-updates-x86_64/kernel-5.11.11-100.fc32.x86_64.rpm.html)), see #126, so it seems to be a general Linux-issue.

**Comment by Abbe98** [comment]
File.listFiles does not return files in "any particular order", the fix above simply sorts it with Arrays.sort().
