### ISSUE TITLE
A file title with special characters, like #, stalls the process

### ISSUE THREAD

**Issue by antoine2711** [yarl/pattypan#113]
I'm trying to push an image and I want it's name to be "Affiche_205_Nuit_#1_Fr.jpg".
But it stalls, without giving an error.

If I try to import it thru the original importer directly on Commons, the file gets changed with a confirmation form to "Affiche_205_Nuit_-1_Fr.jpg".

Regards, Antoine

**Comment by Pyb75** [comment]
The same for [ ].

**Comment by belett** [comment]
Same for all forbidden characters in Mediawiki title (see https://www.mediawiki.org/wiki/Manual:Page_title for full list, maybe not all can be dealt with but at least the more common).

**Comment by Abbe98** [comment]
Thanks @belett, that list is very useful.
