### ISSUE TITLE
STL files, now allowed on Commons, are ignored.

### ISSUE THREAD

**Issue by abartov** [yarl/pattypan#117]
Expected behavior: STL files are uploadable.

**Comment by Abbe98** [comment]
[STL files should be supported.](https://github.com/yarl/pattypan/blob/master/src/pattypan/Util.java#L140) 

When you say they are ignored do you mean that Pattypan does not discover them during spreadsheet creation?

**Comment by abartov** [comment]
Yes, that's the behavior reported by a user on the Wikimedia Commons channel on Telegram.  I filed this issue as a courtesy. I have not seen the behavior myself.

**Comment by abartov** [comment]
"When I started to generate the spreadsheet and navigate to the folder where I had the files, the system saw the folder but not the contents. 
No error message, nothing. As if the folder was empty. I was on a Windows computer and installed the most recent version of Pattypan."
