### ISSUE TITLE
[Bug] use any reasonable upload-order, like every other upload-tool

### ISSUE THREAD

**Issue by JoKalliauer** [yarl/pattypan#126]
Many [SVG-files get blocked due to security reasons](https://commons.wikimedia.org/wiki/User:JoKalliauer/IllegalSVGPattern), so they get an error-message.

Since it always jumps to the current upload, it is difficult to check the errors during upload.

If the files would be uploaded alphabetically, this would be easier to find a specific file in a folder. I know it can be done using excel.exe or Libre-office-calc. I think a button in pattypan for alphabetical sort the *.xls-file would be easy to implement.

**Comment by Abbe98** [comment]
Maybe the documentation could be improved to suggest one does this in their spreadsheet tool, duplicating features from spreadsheet tools could go out of hand.

**Comment by JoKalliauer** [comment]
> Maybe the documentation could be improved to suggest one does this in their spreadsheet tool, duplicating features from spreadsheet tools could go out of hand.

Thanks, I must rename my Question. I don't want spreedsheets-features in pattypan, I just want that pattypan uses any reasonable order, as Upload-Wizard, Come-On, Commonist, VicuñaUploader, pywikibot ...

All of them upload them in order (at least if a single folder, without subfolders), only pattypan is different. So it is a bug, not a feature-request.
I don't mind if pattypan uses alphabetical order, date, ... , but not randomizing it.

I understand that randomizing it, can make sense if you check only the first files, or you want to stop (get blocked) before all mistakes of the same group are uploaded. However randomizing should be opt-in not opt-out.

**Comment by Abbe98** [comment]
#109

**Comment by JoKalliauer** [comment]
@Abbe98 : Thanks I'm using Fedora 32 (I should have reported it, I thought it's irrelevant), Duplicate #109 (I might forgot to check it for this issue, or I did not found it).

**Operating System:**
`Linux version 5.11.11-100.fc32.x86_64 (mockbuild@bkernel02.iad2.fedoraproject.org) (gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9), GNU ld version 2.34-6.fc32) #1 SMP Tue Mar 30 16:53:59 UTC 2021`
