### ISSUE TITLE
XLS Feature CONCATENATE not accepted

### ISSUE THREAD

**Issue by JoKalliauer** [yarl/pattypan#130]
I wanted to use

[pattypan 2021-04-11 15_49_26.xls](https://github.com/yarl/pattypan/files/6291932/pattypan.2021-04-11.15_49_26.xls)

However it seems the CONCATENATE-funktion is not recognised by pattypan.

----
I forgot the ".png", but that's not the issue here.

**Comment by Abbe98** [comment]
CONCATENATE is a Excel feature and not a part of the XLS format as far as I know. No Excel functions should be executed in Pattypan. You can however set the cell to the result of your formula in Excel: https://support.microsoft.com/en-us/office/replace-a-formula-with-its-result-38001951-c0e8-4fbd-9048-37ef81e2891e

**Comment by JoKalliauer** [comment]
XLS is a "EXCEL Spreedsheet", so if it is a Excel-feature till Excel 2003 it is part of the XLS format.

PS: I am using Libre Office.
