### ISSUE TITLE
Installing Pattypan on Windows 20H2 fails

### ISSUE THREAD

**Issue by Sara1211** [yarl/pattypan#135]
Hi, 

I know a similar error was solved, but I tried to follow the steps suggested on the closed issue and could not solve my problem. 

I downloaded the latest Pattypan version and the java version as illustrated in the manual, but as I try to open it, the Command Prompt opens and immediately closes (it sort of flashes once). I tried working with the Command Prompt (my laptop is a Windows 10 Home, version 20H2 if that can help), and this is the output. 

>java -jar pattypan.jar
Error: Could not find or load main class pattypan.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

>java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

The past issue was closed by the user as using v.17.12 solved the problem for them - again, I tried it but it didn't work for me. I'm sorry if this is easy to solve, I'm kind of new to Pattypan and not sure about how this should work.
.

**Comment by Abbe98** [comment]
At this point in time Pattypan does not work with Java 11 or later, you have Java 16 installed.

**Comment by Sara1211** [comment]
> 
> 
> At this point in time Pattypan does not work with Java 11 or later, you have Java 16 installed.

I uninstalled Java 16 and installed Java 8, but it is still not working:

>java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

>java -Duser.language=en -jar pattypan.jar
Error: Unable to access jarfile pattypan.jar

**Comment by Abbe98** [comment]
Given the new error, try running it with admin rights might help. Otherwise one of answers here might help: https://stackoverflow.com/questions/11943948/what-causes-unable-to-access-jarfile-error?page=1&tab=votes

**Comment by Abbe98** [comment]
Pattypan now does not only support Java 11+ but requires it.
