### ISSUE TITLE
Upload sound files .wav .ogg

### ISSUE THREAD

**Issue by Hansmuller2** [yarl/pattypan#14]
Dear Yarl,

Thank you for Pattypan! If possible it would be nice to be able to upload sound files with Pattypan as well, for example of the type

   https://commons.wikimedia.org/wiki/File:Barbitistes_serricauda_-_sound.wav

Compare the list of allowed sound file types on Commons at https://commons.wikimedia.org/wiki/Commons:File_types#Sound .

Thank you for considering this question, best regards, 

hans muller
https://commons.wikimedia.org/wiki/User:Hansmuller

**Comment by yarl** [comment]
Added in version 0.5.
