### ISSUE TITLE
21.10-experimental uploading proces failure

### ISSUE THREAD

**Issue by Aktron** [yarl/pattypan#143]
While testing 21.10-experimental I was able to successfully log in, but I once I hit "upload" no uploading started whatsoever. Then I stopped the upload after couple of minutes. 

I believe this might be related to this type of error: https://github.com/ritschwumm/commonist/issues/26 Then again it might be something else, but this error is something I was afraid might come :-/

The system monitor shows that data were sent: https://ibb.co/FhjFzGJ but it seems that for some reason they were rejected without any error message :-/

Here is my log report:

aktron@aktron-ntb:~/Stažené$ java --module-path "/usr/share/openjfx/lib" --add-modules javafx.web -jar p21.jar
říj 15, 2021 10:19:21 ODP. pattypan.Main main
INFO: Wiki set as: commons.wikimedia.org
Protocol set as: https://
Script path set as: /w
říj 15, 2021 10:19:21 ODP. pattypan.Main main
INFO: Operating System: Linux
Pattypan Version: 21.10
říj 15, 2021 10:19:46 ODP. Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=login
říj 15, 2021 10:19:47 ODP. Wiki login
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=login
říj 15, 2021 10:19:49 ODP. Wiki getUserInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&usprop=editcount%7Cgroups%7Crights%7Cemailable%7Cblockinfo%7Cgender%7Cregistration&maxlag=5&format=xml&action=query&list=users
říj 15, 2021 10:19:49 ODP. Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
říj 15, 2021 10:19:50 ODP. Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
říj 15, 2021 10:19:50 ODP. Wiki getUsers
INFO: [commons.wikimedia.org] Successfully retrieved user info for 1 users.
říj 15, 2021 10:19:50 ODP. Wiki login
INFO: [commons.wikimedia.org] Successfully logged in as Aktron, highLimit = false
říj 15, 2021 10:19:52 ODP. Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
říj 15, 2021 10:19:52 ODP. Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
říj 15, 2021 10:19:52 ODP. Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
říj 15, 2021 10:19:53 ODP. Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
říj 15, 2021 10:19:53 ODP. Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
říj 15, 2021 10:19:53 ODP. Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
aktron@aktron-ntb:~/Stažené$

**Comment by Abbe98** [comment]
@Aktron thanks for testing! It's very valuable to me as I try to ensure that we can have a new stable release as soon as possible.

**Comment by Abbe98** [comment]
@Aktron would you say that this issue is behaving the same way as #145?

**Comment by Aktron** [comment]
@Abbe98: No, these are two different errors. #143 is about a failure of Pattypan to log in. #145 means that I can log in and the upload starts. However it stops after cca 10-30 images. Sometimes even 100 can go through and then it stops. 

Now I am very grateful that there are new releases (exp3 and exp4). Unfortunately I have no batch of images to test it (I've already requested some but it will take some time) to test it right now, but I belive any of these two might solve the issue. Let's see.

**Comment by Abbe98** [comment]
There has been a report of a user not being able to log in once again after a completed upload, it might be something going on.

**Comment by Abbe98** [comment]
Closing but watching feedback as 22.02 is now available.
