### ISSUE TITLE
"GOAWAY received."

### ISSUE THREAD

**Issue by Emilius123** [yarl/pattypan#144]
While uploading, (with @Kartkod 's 21.10-experimental), every single upload gets rejected. The error is always "GOAWAY received". 

My log looks as following:
`Okt. 17, 2021 12:32:51 PM pattypan.Main main
INFO: Wiki set as: commons.wikimedia.org
Protocol set as: https://
Script path set as: /w
Okt. 17, 2021 12:32:51 PM pattypan.Main main
INFO: Operating System: Windows 10
Pattypan Version: 21.10
Okt. 17, 2021 12:33:04 PM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=login
Okt. 17, 2021 12:33:04 PM Wiki login
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=login
Okt. 17, 2021 12:33:05 PM Wiki getUserInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&usprop=editcount%7Cgroups%7Crights%7Cemailable%7Cblockinfo%7Cgender%7Cregistration&maxlag=5&format=xml&action=query&list=users
Okt. 17, 2021 12:33:06 PM Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
Okt. 17, 2021 12:33:06 PM Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
Okt. 17, 2021 12:33:06 PM Wiki getUsers
INFO: [commons.wikimedia.org] Successfully retrieved user info for 1 users.
Okt. 17, 2021 12:33:06 PM Wiki login
INFO: [commons.wikimedia.org] Successfully logged in as Emilius123, highLimit = false
Okt. 17, 2021 12:33:08 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Okt. 17, 2021 12:33:08 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Okt. 17, 2021 12:33:08 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Okt. 17, 2021 12:33:08 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Okt. 17, 2021 12:33:08 PM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
Okt. 17, 2021 12:33:08 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Okt. 17, 2021 12:33:08 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Okt. 17, 2021 12:33:09 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Okt. 17, 2021 12:33:09 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Okt. 17, 2021 12:33:18 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Okt. 17, 2021 12:33:18 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Okt. 17, 2021 12:33:18 PM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
Okt. 17, 2021 12:33:18 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Okt. 17, 2021 12:33:18 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Okt. 17, 2021 12:33:19 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Okt. 17, 2021 12:33:19 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.`

**Comment by Tilman2007** [comment]
Even with 21.10-experimental-2, every single upload gets rejected. The error is always "GOAWAY received".
Protocol:
Nov. 01, 2021 12:42:34 AM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Nov. 01, 2021 12:42:34 AM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Nov. 01, 2021 12:42:34 AM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
Nov. 01, 2021 12:42:34 AM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Nov. 01, 2021 12:42:34 AM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Nov. 01, 2021 12:42:35 AM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Nov. 01, 2021 12:42:35 AM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Nov. 01, 2021 12:42:44 AM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Nov. 01, 2021 12:42:44 AM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Nov. 01, 2021 12:42:44 AM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
Nov. 01, 2021 12:42:44 AM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Nov. 01, 2021 12:42:44 AM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Nov. 01, 2021 12:42:45 AM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Nov. 01, 2021 12:42:45 AM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Nov. 01, 2021 12:42:54 AM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Nov. 01, 2021 12:42:54 AM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Nov. 01, 2021 12:42:54 AM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
Nov. 01, 2021 12:42:54 AM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Nov. 01, 2021 12:42:54 AM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
Nov. 01, 2021 12:42:55 AM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Nov. 01, 2021 12:42:55 AM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
Nov. 01, 2021 12:43:04 AM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query

**Comment by albertoleoncio** [comment]
I'm getting the same error with "21.10-experimental-2". @Aktron: How do upload without this error? Do you use another OS or does your account have highLimit?

```
C:\Users\Alberto\Downloads>java --module-path C:\Users\Alberto\Downloads\javafx-sdk-17.0.1\lib\ --add-modules javafx.web -jar pattypan-2.jar
nov. 01, 2021 12:33:57 PM pattypan.Main main
INFO: Wiki set as: commons.wikimedia.org
Protocol set as: https://
Script path set as: /w
nov. 01, 2021 12:33:57 PM pattypan.Main main
INFO: Operating System: Windows 10
Pattypan Version: 21.10
nov. 01, 2021 12:34:41 PM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=login
nov. 01, 2021 12:34:42 PM Wiki login
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=login
nov. 01, 2021 12:34:43 PM Wiki getUserInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&usprop=editcount%7Cgroups%7Crights%7Cemailable%7Cblockinfo%7Cgender%7Cregistration&maxlag=5&format=xml&action=query&list=users
nov. 01, 2021 12:34:44 PM Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
nov. 01, 2021 12:34:44 PM Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
nov. 01, 2021 12:34:44 PM Wiki getUsers
INFO: [commons.wikimedia.org] Successfully retrieved user info for 1 users.
nov. 01, 2021 12:34:44 PM Wiki login
INFO: [commons.wikimedia.org] Successfully logged in as ALeoncio (WMB), highLimit = false
nov. 01, 2021 12:34:50 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
nov. 01, 2021 12:34:50 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
nov. 01, 2021 12:34:50 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
nov. 01, 2021 12:34:50 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
nov. 01, 2021 12:34:50 PM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
nov. 01, 2021 12:34:50 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
nov. 01, 2021 12:34:51 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
nov. 01, 2021 12:34:52 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
nov. 01, 2021 12:34:52 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
nov. 01, 2021 12:35:00 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
nov. 01, 2021 12:35:00 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
nov. 01, 2021 12:35:00 PM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
nov. 01, 2021 12:35:00 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
nov. 01, 2021 12:35:01 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
nov. 01, 2021 12:35:02 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
nov. 01, 2021 12:35:02 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
nov. 01, 2021 12:35:10 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
nov. 01, 2021 12:35:10 PM Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
nov. 01, 2021 12:35:10 PM Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
nov. 01, 2021 12:35:12 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
nov. 01, 2021 12:35:13 PM Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
nov. 01, 2021 12:35:14 PM Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
```

**Comment by Aktron** [comment]
Interesting. See the output for upload of first image from a row (I've uploaded cca 200 files today), that I hope will give you more answers:

aktron@aktron-ntb:~/Stažené$ java --module-path "/usr/share/openjfx/lib/" --add-modules javafx.web -jar pp22.jar
lis 01, 2021 6:28:08 ODP. pattypan.Main main
INFO: Wiki set as: commons.wikimedia.org
Protocol set as: https://
Script path set as: /w
lis 01, 2021 6:28:08 ODP. pattypan.Main main
INFO: Operating System: Linux
Pattypan Version: 21.10
lis 01, 2021 6:28:21 ODP. Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=login
lis 01, 2021 6:28:21 ODP. Wiki login
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=login
lis 01, 2021 6:28:23 ODP. Wiki getUserInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&usprop=editcount%7Cgroups%7Crights%7Cemailable%7Cblockinfo%7Cgender%7Cregistration&maxlag=5&format=xml&action=query&list=users
lis 01, 2021 6:28:23 ODP. Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
lis 01, 2021 6:28:23 ODP. Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
lis 01, 2021 6:28:23 ODP. Wiki getUsers
INFO: [commons.wikimedia.org] Successfully retrieved user info for 1 users.
lis 01, 2021 6:28:23 ODP. Wiki login
INFO: [commons.wikimedia.org] Successfully logged in as (Username hidden), highLimit = false
lis 01, 2021 6:28:24 ODP. Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
lis 01, 2021 6:28:24 ODP. Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
lis 01, 2021 6:28:24 ODP. Wiki getPageInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
lis 01, 2021 6:28:25 ODP. Wiki getPageInfo
INFO: [commons.wikimedia.org] Successfully retrieved page info for 1 pages.
lis 01, 2021 6:28:25 ODP. Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
lis 01, 2021 6:28:25 ODP. Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
lis 01, 2021 6:28:32 ODP. Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
lis 01, 2021 6:28:32 ODP. Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
lis 01, 2021 6:28:37 ODP. Wiki getToken
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
lis 01, 2021 6:28:38 ODP. Wiki upload
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&format=xml&action=upload
lis 01, 2021 6:28:40 ODP. Wiki upload
INFO: [commons.wikimedia.org] Successfully uploaded to File:Hrneček (4).jpg.

**Comment by Tilman2007** [comment]
There seems to be a difference between Linux and Windows 10/11. The error occurs with Win10.
The error is shown only in pattypan not in the protocol.
It reads: /<IP>:<some number>:GOAWAY received.
The <some number> changes with every picture and it starts with 50968. With the next picture different numbers are added: +2, +5, +4, +2 etc.  Cannot find any pattern.

**Comment by Tilman2007** [comment]
The error reads: **/IP address:some number:GOAWAY received.**
some number is increased with every picture. Cannot make any sense of that number. Is it the port?

**Comment by albertoleoncio** [comment]
After installing Ubuntu on VirtualBox, along with Java and OpenJFX, I finally managed to load some files into Commons. There really is some difference between systems that make Pattypan on Linux send normally while Pattypan on Windows is rejected by the server. Weird...

> Cannot make any sense of that number. Is it the port?

Since the IP that appeared to me was the IP of my router, I assume that the number next refers to the port of the NAT server.

**Comment by Abbe98** [comment]
@albertoleoncio thank you for your extensive testing, that's very helpful to me as I was unable to reproduce the issue myself!

**Comment by Aktron** [comment]
Hi. Is there any progress in this issue? Thanks.

**Comment by MER-C** [comment]
One possible workaround is downgrading the HTTP connection to HTTP 1.1.

```java
HttpClient hc = HttpClient.newBuilder()
    .connectTimeout(Duration.ofSeconds(30))
    .version(HttpClient.Version.HTTP_1_1);
wiki.setHttpClient(hc);
```

I don't have a means to test the upload code on Windows.

**Comment by annalauraw** [comment]
I tried with an installation of https://github.com/Kartkod/pattypan/releases/tag/v20.10-experimental-2 on Ubuntu 20.04 LTS with VirtualBox, but Pattypan still gets stuck during the upload. Also, in my test spreadsheet with two files, I only get a correct preview for one image, for the other I can see only file name and path.
@albertoleoncio could you share the Java and OpenJFX versions you are using? I have the following:

openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)
javafx-sdk-17.0.1

**Comment by MER-C** [comment]
Just found https://github.com/MER-C/wiki-java/issues/186. HTTP 1.1 downgrade doesn't work.

**Comment by MER-C** [comment]
... and fixed. Uploading should now work on my end.

**Comment by Abbe98** [comment]
Thank you @MER-C! 

[I have made a new experimental release with the updated version of wiki-java.](https://github.com/yarl/pattypan/issues/138#issuecomment-1019478971)

**Comment by Abbe98** [comment]
It has now been confirmed by multiple users that v20.10-experimental-3 fixes this issue.
