### ISSUE TITLE
Not able to login to Commons server from Pattypan - Login failed message, when will this be fixed?

### ISSUE THREAD

**Issue by VinayarajVR** [yarl/pattypan#148]
If you are reporting a bug please:

 - Check the bug has already been reported (https://github.com/yarl/pattypan/issues).
 - Explain the current issue.
 - Describe the expected behavior.
 - Add the problematic spreadsheet and a example media file (drag & drop here).
 - Add the PattyPan log file (drag & drop here). You find a link to the PattyPan log at the application start screen.

**Comment by VinayarajVR** [comment]
Not able to login to Commons server from Pattypan - Login failed message, when will this be fixed?

**Comment by Abbe98** [comment]
The issue is tracked in #138, please see that issue for updates.
