### ISSUE TITLE
Feature request: save constants from previous uploads

### ISSUE THREAD

**Issue by VDK** [yarl/pattypan#16]
Would be nice if  when you switch on a particular value being a constant, the value you used for that constant on a previous upload would appear.

I upload a fair few of my own photographs using Pattypan, so I keep putting in 

{{own}}
[[User:1Veertje|Vera de Kok]]
{{self|CC-BY-SA-4.0|author=Vera de Kok}}

for source, author and license.

I like Pattypan a lot more than Commonist, but this is one thing that Commonist has that Pattypan doesn't.

**Comment by yarl** [comment]
Released in ver. 17.05. Feedback appreciated.
