### ISSUE TITLE
Template documentation links with spaces are broken

### ISSUE THREAD

**Issue by sebastian-berlin-wmse** [yarl/pattypan#163]
Clicking on "Template documentation" in the "Choose column" step splits templates containing spaces. The result is two tabs, one with the each part of the URL.

# Steps to reproduce:
* Click "Generate Spreadsheet".
* Add any directory and click "Next".
* In the "Choose columns" pane under "Template", click "Art Photo".
* Click "Template documentation".

# Actual result
Two new tabs are opened, one with the URL `https://commons.wikimedia.org/wiki/Template:Art` and one with `photo/doc`.

# Expected result
One tab opens with the URL `https://commons.wikimedia.org/wiki/Template:Art Photo/doc`.

# More information
I have only tried this on Ubuntu 20.04 and with Forefox 97.0 as default browser. There is nothing in log about this. Maybe there should be an entry when opening a URL.

**Comment by Abbe98** [comment]
A fix (#164) will be available in the next release.
