### ISSUE TITLE
Blank page after insert spreadsheet

### ISSUE THREAD

**Issue by rtargenton** [yarl/pattypan#22]
After I insert the spreadsheet and verify, a blank page appears, as in the screen capture attached. I tried different versions (5.0 and 6.0), in different computers, all Windows.

[Untitled.zip](https://github.com/yarl/pattypan/files/725523/Untitled.zip)

**Comment by yarl** [comment]
Can you run app using console (`java -jar pattypan.jar`) and paste error message here? Probably there is something specific about your spreadsheet or file you want to upload.

**Comment by DeniseJ-WMNL** [comment]
I have the same problem, it appeared this week. In the second week of december, during some testing, I had no problem. I am using the same spreadsheet now. I did download the new version (17-12)

**Comment by Abbe98** [comment]
@DeniseJ-WMNL could you run PattyPan by using `java -jar pattypan.jar` and check if you get any error message? as described above and share the spreadsheet here?

**Comment by yarl** [comment]
Closing this one in favour of #55.
