### ISSUE TITLE
FLAC file upload not supported

### ISSUE THREAD

**Issue by psubhashish** [yarl/pattypan#26]
<img width="801" alt="screen shot 2017-03-08 at 12 40 50 am copy" src="https://cloud.githubusercontent.com/assets/1258090/23720615/1e8a96aa-0465-11e7-9608-f2ea18d7a5d1.png">
I tried to create a spreadsheet for a folder containing .flac files but it wouldn't show the "Next" button. Can you please add FLAC as it is a lossless open standard and would be very useful? Thanks.

**Comment by psubhashish** [comment]
Hi @yarl, any updates on this?

**Comment by yarl** [comment]
@psubhashish It will be added in the nearest release tomorrow, sorry for waiting.

**Comment by psubhashish** [comment]
Thanks @yarl I downloaded and have already uploaded a [batch](https://commons.wikimedia.org/wiki/Category:Kathabhidhana_uploads_10_May_2017) yesterday. I have a quick update for you. I not only have added your amazing tool to my [tookit](https://github.com/OdiaWikimedia/Kathabhidhana) but I'm also making a tutorial about how to use Pattypan.

**Comment by yarl** [comment]
Perfect :) You should consider add it as a [learning pattern on meta](https://meta.wikimedia.org/wiki/Grants:Learning_patterns).
