### ISSUE TITLE
Retry button for failed uploads

### ISSUE THREAD

**Issue by psubhashish** [yarl/pattypan#27]
Currently there is no option to retry failed uploads. Even a much slower uploader like Upload Wizard has this option. And an efficient batch uploader like Pattypan should have this option. Right now one has to search for the error message that looks like this:
<img width="759" alt="screen shot 2017-03-12 at 9 04 02 am" src="https://cloud.githubusercontent.com/assets/1258090/23828772/7de43ca6-0702-11e7-98c2-2e1031f77514.png">
`[10/99] Error: Operation timed out (Connection timed out).`
where 10 and 99 being variables where 10 is the 10th file and 99 is the total number of files in the batch, and upload again by removing the uploaded files from the spreadsheet, and run Pattypan again. It would be great to include the feature of retrying to upload the failed uploads. Thanks in advance!

**Comment by psubhashish** [comment]
Hi, any updates on this?

**Comment by yarl** [comment]
Released in ver.17.05.

**Comment by psubhashish** [comment]
Thanks a lot @yarl
