### ISSUE TITLE
Change name button 'back to start' to 'continue and upload' 

### ISSUE THREAD

**Issue by Lanbot84** [yarl/pattypan#32]
Hi Jarl, 

Firstly: thank you for creating this great tool! I have been working as WiR with GLAMs in the Netherlands learning them to use it, and I would like to share a suggestion they made. 

In step three, when you finish generating your spreadsheet and proceed to uploading, the button is labeled 'back to start'. This confused the employees using the tool, because they tought they would undo there process and were looking for something to continue the process. Therefore, it might be a good idea to change the name of the button to 'continue and upload' or something like that. 

Cheers and keep up the good work! 

Best wishes, 
Michelle 

By the way, let me know if there are special things you want to user test with GLAM employees, my residency continues to run till the end of this year.

**Comment by yarl** [comment]
I totally agree. Can you give me Dutch translation of `Continue and upload`? I will include it in next version of pattypan.

**Comment by Lanbot84** [comment]
Hi Yarl,

Great, thanks for this! The Dutch translation for 'continue and upload' 
is 'doorgaan en uploaden'.

Looking forward to the next version of Pattypan, let me know if there is 
anything else I can do to help to test the tool.

Best wishes,

Michelle

**Comment by yarl** [comment]
Released in ver.17.05.
