### ISSUE TITLE
remove previous uploads from validate and upload screen

### ISSUE THREAD

**Issue by Lanbot84** [yarl/pattypan#33]
Hi Jarl, 

Another thing that was pointed out to me while using the tool at GLAM offices  (see #32) is that when you change the files you upload, or add other you want to upload, the previous uploads you did before that stay visible at the last step in the upload screen. This made people question whether they got the process right and made them 'afraid' to upload the same image again. 

Maybe this could be adjusted? 

Thanks! 

Michelle

**Comment by yarl** [comment]
Released in ver.17.05.
