### ISSUE TITLE
Failing to upload larger files

### ISSUE THREAD

**Issue by psubhashish** [yarl/pattypan#37]
I have been trying a 283 MB and 107 MB file one at a time. But have not been able to upload them after multiple attempts. Each time I try to upload them it takes a few minutes and I see an update on Pattypan saying it has failed to upload. Any particular reason?

**Comment by yarl** [comment]
Well, it probably should work. Per [discussion on facebook](https://www.facebook.com/groups/wikipediaweekly/permalink/1332864890094672/), have you tried again?

**Comment by psubhashish** [comment]
Yup, it's working now. Maybe it was a server issue.
