### ISSUE TITLE
Metadata fields for Template:Book misrepresented

### ISSUE THREAD

**Issue by Hansmuller2** [yarl/pattypan#39]
Dear Pawel,

Thanks for Pattypan 17.05, it is great! Extending the Simple Manual with some examples, I just hit upon your use of the metadata Template:Book https://commons.wikimedia.org/wiki/Template:Book/doc and it appears something is wrong with the data fields presented in the field selection menu. 
1. At the end the fields License and Partnership occur 2 times. 
2. The names of the fields sometimes differ slightly from their definition, e.g., "Page overview" instead of "Pageoverview" and "Home category" instead of "Homecat". I didn't test if this a problem with an upload.

 Yours sincerely, Hans Muller 
https://commons.wikimedia.org/wiki/User:Hansmuller

**Comment by yarl** [comment]
> At the end the fields License and Partnership occur 2 times.

[You are totally right](https://github.com/yarl/pattypan/blob/master/src/pattypan/Settings.java#L183-L186)

> The names of the fields sometimes differ slightly from their definition

This one [should be fine](https://github.com/yarl/pattypan/blob/master/src/pattypan/Settings.java#L173). "Page overview" is just a label in Pattypan and in the future it will be translatable.

**Comment by yarl** [comment]
Fixed in 17.12.
