### ISSUE TITLE
Timestamp is being written in US date format

### ISSUE THREAD

**Issue by VDK** [yarl/pattypan#4]
in de spreadsheet my dates were formatted: 
7-7-2011  12:22:00

This was translated upon uploading into US date format:

7/7/11 12:22

This is a format Mediawiki doesn't understand, the proper format would have been:

2011-07-07 12:22:00

**Comment by yarl** [comment]
This one is fixed [some time ago](https://github.com/yarl/pattypan/commit/bff23541182d0f8b6589820d64533892ab9edb41#diff-36e5a4a28bc8208477445f8947204827R162) but wasn't released until now. Please take a look at [brand new version 0.2](https://github.com/yarl/pattypan/releases) 👌  .

Right now hours are cut out, however. If you consider hour important, I can probably add it

**Comment by VDK** [comment]
What time of day a picture was taken is sort of relevant. I've seen a guy use it once to add a geotag to an image.

**Comment by VDK** [comment]
I've fixed the dates of all Pattypan's uploads. Here is the code that I used to fix the way approximate dates were printed:

```
if (preg_match('/(ca. )?([0-9]{4}) ?. ?(ca. )?([0-9]{4})/', $photo_date, $matches)){
	$date = "{{other date|".($matches[1]? "~":"Between")."|".$matches[2]."|".$matches[4]."}}";
}

elseif (preg_match('/([0-9]{4})\/([0-9]{1,2})\/([0-9]{1,2})/', $photo_date, $matches)){
	$date = $matches[1]."-".$matches[2]."-".$matches[3];
}
elseif (preg_match('/([0-9]{1,2})\D([0-9]{1,2})\D([0-9]{4})/', $photo_date, $matches)){
	$date = $matches[3]."-".$matches[2]."-".$matches[1];
}
elseif (preg_match('/(<|Before) ?([0-9]{4})/', $photo_date, $matches)){
	$date = "{{other date|<|".$matches[2]."}}";
}
elseif (preg_match('/> ?([0-9]{4})/', $photo_date, $matches)){
	$date = "{{other date|>|".$matches[1]."}}";
}
	elseif (preg_match('/(ca.|um) ?([0-9]{4})/', $photo_date, $matches)){
	$date = "{{other date|~|".$matches[2]."}}";
}
	elseif (preg_match('/([0-9]{4})\.([0-9]{2})\./', $photo_date, $matches)){
	$date = $matches[1]."-".$matches[2];
}
elseif ($photo_date == 'Entstehungszeit unbekannt' ||  $photo_date =='s.d.'){
	$date = "{{other date|unknown}}";
}
```

**Comment by yarl** [comment]
This one is done I guess.
