### ISSUE TITLE
Preview substitute page does not generate {{subst:OP}} template

### ISSUE THREAD

**Issue by Lanbot84** [yarl/pattypan#68]
Hi guys, 

When I add an {{subst:OP}} template (for pending OTRS requests) to the permission field, the template does not generate a label in preview mode. See [here](https://commons.wikimedia.org/wiki/Special:ExpandTemplates?wpRemoveComments=true&wpInput=%3D%3D%7B%7Bint%3Afiledesc%7D%7D%3D%3D%0A%7B%7BArtwork%0A+%7Cartist+%3D+Torii+Kiyonaga+%28Vervaardiging%29%0A+%7Cauthor+%3D+%0A+%7Ctitle+%3D+%0A+%7Cdescription+%3D+%7B%7Bnl%7C1%3DTwee+jonge+vrouwen%2C+een+zittend%2C+een+staand%2C+in+een+kamer.+De+schuifdeuren+zijn+opengeschoven+en+geven+uitzicht+over+de+veranda+%28Japans%3A+engawa%29+en+de+tuin%2C+waar+onder+andere+bamboegras+%28sasa%29+groeit.%0AHet+thema+van+de+serie%2C+%27De+Acht+gezichten%27%2C+is+klassiek+in+de+Japanse+prentkunst.+Oorspronkelijk+werden+hiermee+acht+gezichten+om+het+Biwa-meer+bedoeld+onder+speciale+omstandigheden+van+het+klimaat.+Vanaf+Harunobu%27s+tijd+werd+het+gezichten+in+of+om+Edo%2C+huiselijke+tafereeltjes+of+sc%C3%A8nes+in+een+uitgaanswijk.+Hoewel+Kiyonaga+een+telg+was+uit+de+familie+der+Torii%2C+die+zich+van+oudsher+had+gespecialiseerd+in+acteursprenten%2C+vormen+prenten+met+mooie+vrouwen+het+leeuwendeel+van+zijn+oeuvre.+Het+vroege+werk+van+Kiyonaga+vertoont+nog+sterk+de+invloed+van+Kory%C3%BBsai+met+wie+hij+werkte+aan+grote+serie+van+meer+dan+140+prenten%3A+%27Voorbeeld+patronen+voor+jong+lentegroen%27+%28Hinagata+wakana+no+hatsu+moy%C3%B4%29.+Kiyonaga+werkte+vanaf+1777+voor+de+bekende+uitgever+Nishimuraya+Yohachi+voor+wie+hij+enkele+van+zijn+meest+spectaculaire+triptieken+zou+maken.%0A%0AUitgever%3A+Nishimuraya+Yohachi%7D%7D%0A+%7Cdate+%3D+1779%0A+%7Cmedium+%3D+%7B%7Bnl%7C1%3Dpapier+%3B+inkt+%3B+pigmenten+%3B+drukwerk+%3B+houtsnede+%3B+kleurenhoutsnede+%28nishikie%29%7D%7D%0A+%7Cdimensions+%3D+%0A+%7Cinstitution+%3D+Nationaal+Museum+van+Wereldculturen%0A+%7Cdepartment+%3D+%0A+%7Cobject+history+%3D+%0A+%7Cexhibition+history+%3D+%0A+%7Ccredit+line+%3D+%0A+%7Cinscriptions+%3D+%0A+%7Cnotes+%3D+%7B%7Bnl%7C1%3DMooie-vrouwen-prent%7D%7D%0A+%7Caccession+number+%3D+RV-3980-7%0A+%7Cplace+of+creation+%3D+%7B%7Bnl%7C1%3DT%C3%B4ky%C3%B4+To%2C+Ukiyo-e%7D%7D%0A+%7Csource+%3D+%5Bhttps%3A%2F%2Fhdl.handle.net%2F20.500.11840%2F784467+View+this+image+on+the+website+of+the+Museum+van+Wereldculturen%5D%0A+%7Cpermission+%3D%7B%7Bsubst%3AOP%7D%7D%0A+%7Cother_versions+%3D+%0A+%7Creferences+%3D+%0A+%7Cwikidata+%3D+%0A%7D%7D%0A%0A%3D%3D%7B%7Bint%3Alicense-header%7D%7D%3D%3D%0A%7B%7BNMvW-license%7D%7D%0A%7B%7BThe+Netherlands+and+the+world%7D%7D%0A%0A%5B%5BCategory%3AImages+from+Nationaal+Museum+van+Wereldculturen+2018_03_07%5D%5D%0A%0A%5B%5BCategory%3AUploaded+with+pattypan%5D%5D&wpContextTitle=Elegante+afbeelding+van+mooie+vrouw-+Stichting+Nationaal+Museum+van+Wereldculturen+-+RV-3980-7.jpg)

I think it is because the label has recently been changed or something. 
If you can't do anything about it let me know where I should report this! 

Thanks for all the hard work! 

Michelle

**Comment by yarl** [comment]
Hey @Lanbot84, for some reason this is how `Special:ExpandTemplates` works. Probably you can report it on Phabricator, there is [MediaWiki-Special-pages](https://phabricator.wikimedia.org/project/profile/133/) project for that.
