### ISSUE TITLE
overwriting 2500 svg-files, without description-change (bug-fix for renderissue)

### ISSUE THREAD

**Issue by JoKalliauer** [yarl/pattypan#83]
pattypan v.18.02
    Linux 4.15.0-34-generic amd64 
    Java 1.8.0_181

I want to bug-fix a renderissue: [phab:T36947](https://phabricator.wikimedia.org/T36947) for more than 2500+[1] svg-files:

How can I overwrite the files without changing the description?
If I try to upload a empty template I get "Error: empty template!".
Can I create a spreadsheed that contains the actual description? If I reupload the same, wikimedia should not create new history-version if it is completely identical.)
Or is it possible to upload files without description?

This issue is maybe related to: https://github.com/ritschwumm/commonist/issues/19

Please provide an reasonable upload for minor (but necessary) mass-bug-fix-edits, such as [User_talk:JoKalliauer#Text_rendering](https://commons.wikimedia.org/wiki/User_talk:JoKalliauer#Text_rendering)

[1] [Category:SVG_maps_showing_history_in_Russian](https://commons.wikimedia.org/wiki/Category:SVG_maps_showing_history_in_Russian)

**Comment by JoKalliauer** [comment]
I solved it with [Command-line_upload](https://www.mediawiki.org/wiki/Manual:Pywikibot/upload.py), which seems to be the right choice for such cases.

**Comment by lgelauff** [comment]
@JoKalliauer does your workaround through the API still work? Could you describe it in more detail?

**Comment by JoKalliauer** [comment]
@lgelauff  I use

> python /data/project/shared/pywikipedia/core/scripts/upload.py Test.svg -keep -ignorewarn -noverify -descfile "new version"

see

https://github.com/JoKalliauer/cleanupSVG/blob/master/WorkaroundBotsvg2validsvg.sh#L232

**Comment by lgelauff** [comment]
Thanks. Figured out that I got stuck on having a too young  (bot)account , for overwriting permissions you need to be autoconfirmed.
